#!/usr/bin/env python3
"""
Fix German umlaut substitutions in .tsx files.
Replaces ASCII substitutions (ae→ä, oe→ö, ue→ü, ss→ß) with proper umlauts
using word-boundary matching to avoid corrupting JS/TS identifiers.
"""

import os
import re
from pathlib import Path

# Sorted longest-first to avoid partial matches (e.g. "Geschaeftsfuehrer" before "Geschaeft")
REPLACEMENTS = [
    # ü replacements (ue → ü)
    ("Ueber", "Über"),
    ("ueber", "über"),
    ("Fuer", "Für"),
    ("fuer", "für"),
    ("Fuenf", "Fünf"),
    ("fuenf", "fünf"),
    ("Pruefpunkte", "Prüfpunkte"),
    ("Pruefpunkt", "Prüfpunkt"),
    ("Pruefung", "Prüfung"),
    ("Plagiatspruefung", "Plagiatsprüfung"),
    ("Geprueft", "Geprüft"),
    ("geprueft", "geprüft"),
    ("Fuellen", "Füllen"),
    ("fuellen", "füllen"),
    ("Fuelltext", "Fülltext"),
    ("fuelltext", "fülltext"),
    ("Geschaeftsfuehrer", "Geschäftsführer"),
    ("Geschaeftsfuehrerin", "Geschäftsführerin"),
    ("Natuerlich", "Natürlich"),
    ("natuerlich", "natürlich"),
    ("Kapazitaet", "Kapazität"),
    ("kapazitaet", "kapazität"),
    ("Qualitaet", "Qualität"),
    ("qualitaet", "qualität"),
    ("Agilitaet", "Agilität"),
    ("agilitaet", "agilität"),
    ("Autoritaet", "Autorität"),
    ("autoritaet", "autorität"),
    ("Komplexitaet", "Komplexität"),
    ("komplexitaet", "komplexität"),
    ("Kontinuitaet", "Kontinuität"),
    ("kontinuitaet", "kontinuität"),
    ("Mobilitaet", "Mobilität"),
    ("mobilitaet", "mobilität"),
    ("Flexibilitaet", "Flexibilität"),
    ("flexibilitaet", "flexibilität"),
    ("Stabilitaet", "Stabilität"),
    ("stabilitaet", "stabilität"),
    ("Produktivitaet", "Produktivität"),
    ("produktivitaet", "produktivität"),
    ("Kuendbarkeit", "Kündbarkeit"),
    ("kuendbarkeit", "kündbarkeit"),
    ("Kuendigung", "Kündigung"),
    ("kuendigung", "kündigung"),
    ("kuendbar", "kündbar"),
    ("Kuendbar", "Kündbar"),
    ("Gruender", "Gründer"),
    ("gruender", "gründer"),
    ("Gruenden", "Gründen"),
    ("gruenden", "gründen"),
    ("Begruendung", "Begründung"),
    ("begruendung", "begründung"),
    ("Luecken", "Lücken"),
    ("luecken", "lücken"),
    ("Luecke", "Lücke"),
    ("luecke", "lücke"),
    ("Buerostuhl", "Bürostuhl"),
    ("buerostuhl", "bürostuhl"),
    ("Bauchgefuehl", "Bauchgefühl"),
    ("bauchgefuehl", "bauchgefühl"),
    ("Zurueck", "Zurück"),
    ("zurueck", "zurück"),
    ("Genuegend", "Genügend"),
    ("genuegend", "genügend"),
    ("Verfuegbar", "Verfügbar"),
    ("verfuegbar", "verfügbar"),
    ("Verfuegbarkeit", "Verfügbarkeit"),
    ("verfuegbarkeit", "verfügbarkeit"),

    # ö replacements (oe → ö)
    ("Loesung", "Lösung"),
    ("loesung", "lösung"),
    ("Loesungen", "Lösungen"),
    ("loesungen", "lösungen"),
    ("Loesungsansatz", "Lösungsansatz"),
    ("Loesungsorientiert", "Lösungsorientiert"),
    ("loesungsorientiert", "lösungsorientiert"),
    ("Koennen", "Können"),
    ("koennen", "können"),
    ("Koennt", "Könnt"),
    ("koennt", "könnt"),
    ("Moeglichkeit", "Möglichkeit"),
    ("moeglichkeit", "möglichkeit"),
    ("Moeglichkeiten", "Möglichkeiten"),
    ("moeglichkeiten", "möglichkeiten"),
    ("Groesse", "Größe"),
    ("groesse", "größe"),
    ("Groessen", "Größen"),
    ("groessen", "größen"),
    ("Bildgroessen", "Bildgrößen"),
    ("bildgroessen", "bildgrößen"),
    ("Goettingen", "Göttingen"),
    ("Boerse", "Börse"),
    ("boerse", "börse"),
    ("Oekosystem", "Ökosystem"),
    ("oekosystem", "ökosystem"),
    ("Oeffentlich", "Öffentlich"),
    ("oeffentlich", "öffentlich"),
    ("Oeffentlichkeit", "Öffentlichkeit"),
    ("oeffentlichkeit", "öffentlichkeit"),
    ("Persoenlich", "Persönlich"),
    ("persoenlich", "persönlich"),
    ("Persoenliche", "Persönliche"),
    ("persoenliche", "persönliche"),
    ("Persoenlicher", "Persönlicher"),
    ("persoenlicher", "persönlicher"),
    ("Persoenliches", "Persönliches"),
    ("persoenliches", "persönliches"),
    ("Persoenlichkeit", "Persönlichkeit"),
    ("persoenlichkeit", "persönlichkeit"),
    ("Orthpaeden", "Orthopäden"),

    # ä replacements (ae → ä)
    ("Massnahme", "Maßnahme"),
    ("massnahme", "maßnahme"),
    ("Massnahmen", "Maßnahmen"),
    ("massnahmen", "maßnahmen"),
    ("Einzelmassnahmen", "Einzelmaßnahmen"),
    ("einzelmassnahmen", "einzelmaßnahmen"),
    ("massgeschneidert", "maßgeschneidert"),
    ("Massgeschneidert", "Maßgeschneidert"),
    ("Geschaeft", "Geschäft"),
    ("geschaeft", "geschäft"),
    ("Geschaefte", "Geschäfte"),
    ("geschaefte", "geschäfte"),
    ("Geschaeftlich", "Geschäftlich"),
    ("geschaeftlich", "geschäftlich"),
    ("Geschaeftsmodell", "Geschäftsmodell"),
    ("geschaeftsmodell", "geschäftsmodell"),
    ("Geschaeftsziel", "Geschäftsziel"),
    ("geschaeftsziel", "geschäftsziel"),
    ("Geschaeftswert", "Geschäftswert"),
    ("geschaeftswert", "geschäftswert"),
    ("Geschaeftsgrundlage", "Geschäftsgrundlage"),
    ("geschaeftsgrundlage", "geschäftsgrundlage"),
    ("Geschaetztes", "Geschätztes"),
    ("geschaetztes", "geschätztes"),
    ("Gespraech", "Gespräch"),
    ("gespraech", "gespräch"),
    ("Ergebnisgespraech", "Ergebnisgespräch"),
    ("ergebnisgespraech", "ergebnisgespräch"),
    ("Erstgespraech", "Erstgespräch"),
    ("erstgespraech", "erstgespräch"),
    ("Fachgespraech", "Fachgespräch"),
    ("fachgespraech", "fachgespräch"),
    ("Haeufig", "Häufig"),
    ("haeufig", "häufig"),
    ("Haeufigkeit", "Häufigkeit"),
    ("haeufigkeit", "häufigkeit"),
    ("Plaene", "Pläne"),
    ("plaene", "pläne"),
    ("Laenge", "Länge"),
    ("laenge", "länge"),
    ("Aenderung", "Änderung"),
    ("aenderung", "änderung"),
    ("Aenderungen", "Änderungen"),
    ("aenderungen", "änderungen"),
    ("Veraenderung", "Veränderung"),
    ("veraenderung", "veränderung"),
    ("Veraenderungen", "Veränderungen"),
    ("veraenderungen", "veränderungen"),
    ("Marktveraenderungen", "Marktveränderungen"),
    ("marktveraenderungen", "marktveränderungen"),
    ("Einschaetzung", "Einschätzung"),
    ("einschaetzung", "einschätzung"),
    ("Einschaetzungen", "Einschätzungen"),
    ("einschaetzungen", "einschätzungen"),
    ("Maerkte", "Märkte"),
    ("maerkte", "märkte"),
    ("Maerkten", "Märkten"),
    ("maerkten", "märkten"),
    ("Nischenmaerkten", "Nischenmärkten"),
    ("nischenmaerkten", "nischenmärkten"),
    ("Maerz", "März"),
    ("maerz", "märz"),
    ("Erklaerung", "Erklärung"),
    ("erklaerung", "erklärung"),
    ("Erklaerungen", "Erklärungen"),
    ("erklaerungen", "erklärungen"),
    ("Qualitaetssicherung", "Qualitätssicherung"),

    # ß replacements (ss → ß where appropriate)
    ("Strassenverzeichnis", "Straßenverzeichnis"),
    ("Strasse", "Straße"),
    ("strasse", "straße"),
    ("Strassen", "Straßen"),
    ("strassen", "straßen"),
    ("Grossunternehmen", "Großunternehmen"),
    ("grossunternehmen", "großunternehmen"),
    ("Grossteil", "Großteil"),
    ("grossteil", "großteil"),
    ("Grossen", "Großen"),
    ("grossen", "großen"),
    ("Grosse", "Große"),
    ("grosse", "große"),

    # --- Additional entries ---
    ("Verlinkungsvorschlaegen", "Verlinkungsvorschlägen"),
    ("Verlinkungsvorschlaege", "Verlinkungsvorschläge"),
    ("Wettbewerbsintensitaet", "Wettbewerbsintensität"),
    ("erfahrungsgemaess", "erfahrungsgemäß"),
    ("Erfahrungsgemaess", "Erfahrungsgemäß"),
    ("stiefmuetterlich", "stiefmütterlich"),
    ("Stiefmuetterlich", "Stiefmütterlich"),
    ("halbjaehrliche", "halbjährliche"),
    ("Halbjaehrliche", "Halbjährliche"),
    ("halbjaehrlichen", "halbjährlichen"),
    ("Halbjaehrlichen", "Halbjährlichen"),
    ("laenderspezifische", "länderspezifische"),
    ("Laenderspezifische", "Länderspezifische"),
    ("laenderspezifischen", "länderspezifischen"),
    ("Projektgroessen", "Projektgrößen"),
    ("projektgroessen", "projektgrößen"),
    ("Standardloesungen", "Standardlösungen"),
    ("standardloesungen", "standardlösungen"),
    ("Strategiegespraech", "Strategiegespräch"),
    ("strategiegespraech", "strategiegespräch"),
    ("Rueckenschmerzen", "Rückenschmerzen"),
    ("rueckenschmerzen", "rückenschmerzen"),
    ("Wirbelsaeule", "Wirbelsäule"),
    ("wirbelsaeule", "wirbelsäule"),
    ("Pruefpunkten", "Prüfpunkten"),
    ("pruefpunkten", "prüfpunkten"),
    ("Vollstaendigkeit", "Vollständigkeit"),
    ("vollstaendigkeit", "vollständigkeit"),
    ("Vollstaendige", "Vollständige"),
    ("vollstaendige", "vollständige"),
    ("Vollstaendiges", "Vollständiges"),
    ("vollstaendiges", "vollständiges"),
    ("vollstaendig", "vollständig"),
    ("Vollstaendig", "Vollständig"),
    ("Verstaendnis", "Verständnis"),
    ("verstaendnis", "verständnis"),
    ("Verzoegerung", "Verzögerung"),
    ("verzoegerung", "verzögerung"),
    ("eigenstaendig", "eigenständig"),
    ("Eigenstaendig", "Eigenständig"),
    ("eigenstaendige", "eigenständige"),
    ("Eigenstaendige", "Eigenständige"),
    ("eigenstaendigen", "eigenständigen"),
    ("ausfuehrlichen", "ausführlichen"),
    ("Ausfuehrlichen", "Ausführlichen"),
    ("ausfuehrlich", "ausführlich"),
    ("Ausfuehrlich", "Ausführlich"),
    ("durchgefuehrt", "durchgeführt"),
    ("Durchgefuehrt", "Durchgeführt"),
    ("durchfuehren", "durchführen"),
    ("Durchfuehren", "Durchführen"),
    ("durchfuehrt", "durchführt"),
    ("ueberzeugende", "überzeugende"),
    ("Ueberzeugende", "Überzeugende"),
    ("ueberzeugender", "überzeugender"),
    ("Ueberzeugender", "Überzeugender"),
    ("ueberzeugend", "überzeugend"),
    ("Ueberzeugend", "Überzeugend"),
    ("ueberzeugen", "überzeugen"),
    ("Ueberzeugen", "Überzeugen"),
    ("ueberzeugt", "überzeugt"),
    ("Ueberzeugt", "Überzeugt"),
    ("uebertriebenen", "übertriebenen"),
    ("Uebertriebenen", "Übertriebenen"),
    ("uebertrieben", "übertrieben"),
    ("Uebertrieben", "Übertrieben"),
    ("uebergreifende", "übergreifende"),
    ("Uebergreifende", "Übergreifende"),
    ("uebergreifenden", "übergreifenden"),
    ("uebergeordnete", "übergeordnete"),
    ("Uebergeordnete", "Übergeordnete"),
    ("uebergeordneten", "übergeordneten"),
    ("ueberarbeitete", "überarbeitete"),
    ("Ueberarbeitete", "Überarbeitete"),
    ("uebernehmen", "übernehmen"),
    ("Uebernehmen", "Übernehmen"),
    ("uebernimmt", "übernimmt"),
    ("Uebernimmt", "Übernimmt"),
    ("uebernahme", "Übernahme"),
    ("Uebernahme", "Übernahme"),
    ("ueberall", "überall"),
    ("Ueberall", "Überall"),
    ("veraenderte", "veränderte"),
    ("Veraenderte", "Veränderte"),
    ("veraenderten", "veränderten"),
    ("Veraenderten", "Veränderten"),
    ("veraendert", "verändert"),
    ("Veraendert", "Verändert"),
    ("tatsaechlichen", "tatsächlichen"),
    ("Tatsaechlichen", "Tatsächlichen"),
    ("tatsaechliche", "tatsächliche"),
    ("Tatsaechliche", "Tatsächliche"),
    ("tatsaechlich", "tatsächlich"),
    ("Tatsaechlich", "Tatsächlich"),
    ("halbjaehrlich", "halbjährlich"),
    ("Halbjaehrlich", "Halbjährlich"),
    ("jaehrliche", "jährliche"),
    ("Jaehrliche", "Jährliche"),
    ("jaehrlichen", "jährlichen"),
    ("Jaehrlichen", "Jährlichen"),
    ("jaehrlich", "jährlich"),
    ("Jaehrlich", "Jährlich"),
    ("regelmaessige", "regelmäßige"),
    ("Regelmaessige", "Regelmäßige"),
    ("regelmaessigen", "regelmäßigen"),
    ("regelmaessig", "regelmäßig"),
    ("Regelmaessig", "Regelmäßig"),
    ("persoenlichen", "persönlichen"),
    ("Persoenlichen", "Persönlichen"),
    ("persoenlichem", "persönlichem"),
    ("persoenlicher", "persönlicher"),
    ("Prioritaeten", "Prioritäten"),
    ("prioritaeten", "prioritäten"),
    ("Prioritaet", "Priorität"),
    ("prioritaet", "priorität"),
    ("Realitaet", "Realität"),
    ("realitaet", "realität"),
    ("Tonalitaet", "Tonalität"),
    ("tonalitaet", "tonalität"),
    ("Schwaechen", "Schwächen"),
    ("schwaechen", "schwächen"),
    ("Schwaechere", "Schwächere"),
    ("natuerliche", "natürliche"),
    ("Natuerliche", "Natürliche"),
    ("natuerlicher", "natürlicher"),
    ("natuerlichen", "natürlichen"),
    ("praesentieren", "präsentieren"),
    ("Praesentieren", "Präsentieren"),
    ("praesentiert", "präsentiert"),
    ("Praesentiert", "Präsentiert"),
    ("praezise", "präzise"),
    ("Praezise", "Präzise"),
    ("praeziser", "präziser"),
    ("Praeziser", "Präziser"),
    ("pruefen", "prüfen"),
    ("Pruefen", "Prüfen"),
    ("prueft", "prüft"),
    ("Prueft", "Prüft"),
    ("staendig", "ständig"),
    ("Staendig", "Ständig"),
    ("staendige", "ständige"),
    ("Staendige", "Ständige"),
    ("staendigen", "ständigen"),
    ("Staendigen", "Ständigen"),
    ("Staerken", "Stärken"),
    ("staerken", "stärken"),
    ("staerker", "stärker"),
    ("Staerker", "Stärker"),
    ("staerkt", "stärkt"),
    ("Staerkt", "Stärkt"),
    ("staerke", "stärke"),
    ("Staerke", "Stärke"),
    ("spaetere", "spätere"),
    ("spaeter", "später"),
    ("Spaeter", "Später"),
    ("spaetesten", "spätesten"),
    ("naechsten", "nächsten"),
    ("Naechsten", "Nächsten"),
    ("naechster", "nächster"),
    ("naechste", "nächste"),
    ("Naechste", "Nächste"),
    ("naechstes", "nächstes"),
    ("muessen", "müssen"),
    ("Muessen", "Müssen"),
    ("muesste", "müsste"),
    ("Muesste", "Müsste"),
    ("klaeren", "klären"),
    ("Klaeren", "Klären"),
    ("klaert", "klärt"),
    ("Klaert", "Klärt"),
    ("kuendigen", "kündigen"),
    ("Kuendigen", "Kündigen"),
    ("kuendigt", "kündigt"),
    ("Kuendigt", "Kündigt"),
    ("schaetzen", "schätzen"),
    ("Schaetzen", "Schätzen"),
    ("schaetzt", "schätzt"),
    ("Schaetzt", "Schätzt"),
    ("unterschaetzen", "unterschätzen"),
    ("Unterschaetzen", "Unterschätzen"),
    ("unterschaetzt", "unterschätzt"),
    ("umkaempften", "umkämpften"),
    ("Umkaempften", "Umkämpften"),
    ("umkaempft", "umkämpft"),
    ("Umkaempft", "Umkämpft"),
    ("Textlaenge", "Textlänge"),
    ("textlaenge", "textlänge"),
    ("begruendet", "begründet"),
    ("Begruendet", "Begründet"),
    ("gruendlich", "gründlich"),
    ("Gruendlich", "Gründlich"),
    ("gruendliche", "gründliche"),
    ("gruendlichen", "gründlichen"),
    ("gruenen", "grünen"),
    ("Gruenen", "Grünen"),
    ("fuehren", "führen"),
    ("Fuehren", "Führen"),
    ("fuehrt", "führt"),
    ("Fuehrt", "Führt"),
    ("gefuehrt", "geführt"),
    ("Gefuehrt", "Geführt"),
    ("gefuehle", "Gefühle"),
    ("Gefuehle", "Gefühle"),
    ("gefuehl", "gefühl"),
    ("Gefuehl", "Gefühl"),
    ("erfuellt", "erfüllt"),
    ("Erfuellt", "Erfüllt"),
    ("erfuellen", "erfüllen"),
    ("Erfuellen", "Erfüllen"),
    ("gefuellt", "gefüllt"),
    ("Gefuellt", "Gefüllt"),
    ("fuettert", "füttert"),
    ("erhaeltlich", "erhältlich"),
    ("Erhaeltlich", "Erhältlich"),
    ("enthaelt", "enthält"),
    ("Enthaelt", "Enthält"),
    ("abhaengig", "abhängig"),
    ("Abhaengig", "Abhängig"),
    ("abhaengige", "abhängige"),
    ("abhaengigen", "abhängigen"),
    ("abgehaengt", "abgehängt"),
    ("Abgehaengt", "Abgehängt"),
    ("befaehigt", "befähigt"),
    ("Befaehigt", "Befähigt"),
    ("haelt", "hält"),
    ("Haelt", "Hält"),
    ("faengt", "fängt"),
    ("Faengt", "Fängt"),
    ("waechst", "wächst"),
    ("Waechst", "Wächst"),
    ("waehrend", "während"),
    ("Waehrend", "Während"),
    ("Waehlen", "Wählen"),
    ("waehlen", "wählen"),
    ("wuerde", "würde"),
    ("Wuerde", "Würde"),
    ("wuerden", "würden"),
    ("Wuerden", "Würden"),
    ("wuerdet", "würdet"),
    ("wuerdest", "würdest"),
    ("zaehlt", "zählt"),
    ("Zaehlt", "Zählt"),
    ("zufaelligen", "zufälligen"),
    ("Zufaelligen", "Zufälligen"),
    ("zufaellige", "zufällige"),
    ("Zufaellige", "Zufällige"),
    ("zufaellig", "zufällig"),
    ("Zufaellig", "Zufällig"),
    ("frueh", "früh"),
    ("Frueh", "Früh"),
    ("fruehe", "frühe"),
    ("Fruehe", "Frühe"),
    ("laedt", "lädt"),
    ("Laedt", "Lädt"),
    ("Saeulen", "Säulen"),
    ("saeulen", "säulen"),
    ("Saeule", "Säule"),
    ("saeule", "säule"),
    ("Woerter", "Wörter"),
    ("woerter", "wörter"),
    ("Ruecken", "Rücken"),
    ("ruecken", "rücken"),
    ("Tuer", "Tür"),
    ("tuer", "tür"),
    ("Stueck", "Stück"),
    ("stueck", "stück"),
    ("Stuecke", "Stücke"),
    ("stuecke", "stücke"),
    ("hoehere", "höhere"),
    ("Hoehere", "Höhere"),
    ("hoeheren", "höheren"),
    ("hoeherer", "höherer"),
    ("hoeher", "höher"),
    ("Hoeher", "Höher"),
    ("dafuer", "dafür"),
    ("Dafuer", "Dafür"),
    ("aendert", "ändert"),
    ("Aendert", "Ändert"),
    ("aenderte", "änderte"),
    ("aendern", "ändern"),
    ("Aendern", "Ändern"),
]

# Sort replacements longest-first to avoid partial replacement issues
# e.g. "Geschaeftsfuehrer" must be replaced before "Geschaeft" and "fuehrer"
REPLACEMENTS_SORTED = sorted(REPLACEMENTS, key=lambda x: len(x[0]), reverse=True)

# Build a single compiled regex with word-boundary matching for all patterns
# We use \b where the pattern starts/ends with a word character
def make_pattern(word):
    escaped = re.escape(word)
    # Add word boundary at start if first char is a word char
    prefix = r'\b' if re.match(r'\w', word[0]) else ''
    # Add word boundary at end if last char is a word char
    suffix = r'\b' if re.match(r'\w', word[-1]) else ''
    return prefix + escaped + suffix

def fix_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        original = f.read()

    content = original
    changes = []

    for old, new in REPLACEMENTS_SORTED:
        pattern = make_pattern(old)
        count = len(re.findall(pattern, content))
        if count > 0:
            content = re.sub(pattern, new, content)
            changes.append((old, new, count))

    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return changes
    return []


def main():
    base_dir = Path('/home/eko/designertest/p1-seoforge/src/app')
    tsx_files = sorted(base_dir.rglob('*.tsx'))

    total_files_changed = 0
    total_replacements = 0
    grand_summary = {}

    print(f"Scanning {len(tsx_files)} .tsx files in {base_dir}\n")
    print("=" * 70)

    for filepath in tsx_files:
        changes = fix_file(filepath)
        if changes:
            total_files_changed += 1
            rel = filepath.relative_to(base_dir)
            print(f"\n[CHANGED] {rel}")
            for old, new, count in changes:
                print(f"  {old!r:35s} -> {new!r}  (x{count})")
                total_replacements += count
                grand_summary[old] = grand_summary.get(old, 0) + count

    print("\n" + "=" * 70)
    print(f"SUMMARY: {total_files_changed} files changed, {total_replacements} total replacements")

    if grand_summary:
        print("\nTop replacements across all files:")
        for old, count in sorted(grand_summary.items(), key=lambda x: x[1], reverse=True)[:20]:
            new = next(n for o, n in REPLACEMENTS if o == old)
            print(f"  {old:35s} -> {new}  (total: {count})")


if __name__ == '__main__':
    main()
